var res = {
    HelloWorld_png : "res/HelloWorld.png",
    Xibao_png : "res/celldetailScene/xibao3.png",
    Xibao2_png : "res/celldetailScene/xibao3_2.png",
    startbg : "res/StartImages/startbg.png",
    startbtn : "res/StartImages/startbtn.png",
    aboutusbtn : "res/StartImages/aboutus.png",
    pokedexbg : "res/PokedexImages/pokedexbg.jpg",
    poketumour : "res/PokedexImages/poketumour.png",
    pokecell : "res/PokedexImages/pokecell.png",
    pokecellbtn : "res/PokedexImages/pokecellbutton.png",
    poketumourbtn : "res/PokedexImages/poketumourbutton.png",
    pokereturnbtn : "res/PokedexImages/returnbutton.png",
    display1:"res/PokedexImages/display1.jpg",
    display2:"res/PokedexImages/display2.jpg",
    celldisplay:"res/CellImages/celldisplay.png",
    celldisplay2:"res/CellImages/celldisplay2.png",
    cellgrid:"res/CellImages/cellgrid.png",
    blackboard:"res/CellImages/blackboard.png",
    cell1:"res/CellImages/cell1_2.png",
    cell2:"res/CellImages/cell2_2.png",
    cell3:"res/CellImages/cell3_2.png",
    cell4:"res/CellImages/cell4_2.png",
    cell5:"res/CellImages/cell5_2.png",
    cell6:"res/CellImages/cell6_2.png",
    cell7:"res/CellImages/cell7_2.png",
    cell12:"res/CellImages/cell1.png",
    cell22:"res/CellImages/cell2.png",
    cell32:"res/CellImages/cell3.png",
    cell42:"res/CellImages/cell4.png",
    cell52:"res/CellImages/cell5.png",
    cell62:"res/CellImages/cell6.png",
    cell72:"res/CellImages/cell7.png",
    tumour1:"res/TumourImages/tumour1.png",
    tumour2:"res/TumourImages/tumour2.png",
    tumour3:"res/TumourImages/tumour3.png",
    tumour4:"res/TumourImages/tumour4.png",
    tumour5:"res/TumourImages/tumour5.png",
    tumour6:"res/TumourImages/tumour6.png",
    tumour7:"res/TumourImages/tumour7.png",
    tumour12:"res/TumourImages/tumour1_2.png",
    tumour22:"res/TumourImages/tumour2_2.png",
    tumour32:"res/TumourImages/tumour3_2.png",
    tumour42:"res/TumourImages/tumour4_2.png",
    tumour52:"res/TumourImages/tumour5_5.png",
    tumour62:"res/TumourImages/tumour6_2.png",
    tumour72:"res/TumourImages/tumour7_2.png",
    pressed:"res/CellImages/share_setting_pressed.png",
    pressed2:"res/CellImages/share_setting_pressed_2.png"
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
